name: Test

on: [push, 'pull_request']

jobs:

  win64:
    name: Test on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install latests rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true
      # Selecting a toolchain either by action or manual `rustup` calls should happen before this as
      # the cache uses the current rustc version as its cache key
      - name: build Rust cache
        uses: Swatinem/rust-cache@v2
      - name: Test
        run: cargo test

  osx:
    name: Test MacOS
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install latests rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true
      # Selecting a toolchain either by action or manual `rustup` calls should happen before this as
      # the cache uses the current rustc version as its cache key
      - name: build Rust cache
        uses: Swatinem/rust-cache@v2
      - name: Test
        run: cargo test

  linux:
    name: Test Linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install latests rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true
      # Selecting a toolchain either by action or manual `rustup` calls should happen before this as
      # the cache uses the current rustc version as its cache key
      - name: build Rust cache
        uses: Swatinem/rust-cache@v2
      - name: Test
        run: cargo test

  dependabot:
    needs: [linux,win64,osx]
    permissions:
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request'}}
    steps:
      - name: Merge Depenabot Pull Request
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}